# Generated by Django 4.2.10 on 2024-06-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Blog Category'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Blogs', 'verbose_name_plural': 'Blogs'},
        ),
    ]
