# Generated by Django 4.2.10 on 2024-07-02 08:30

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('blog', '0002_translatedtag_translatedtaggeditem_alter_post_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translatedtaggeditem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='translatedtaggeditem',
            name='tag',
        ),
        migrations.AlterUniqueTogether(
            name='translatedtagtranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='translatedtagtranslation',
            name='master',
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags'),
        ),
        migrations.DeleteModel(
            name='TranslatedTag',
        ),
        migrations.DeleteModel(
            name='TranslatedTaggedItem',
        ),
        migrations.DeleteModel(
            name='TranslatedTagTranslation',
        ),
    ]
