# Generated by Django 4.2.10 on 2024-06-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_remove_post_auther_remove_post_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contacts', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
    ]
