# Generated by Django 4.2.10 on 2024-06-27 02:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='about/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='about',
            name='our_gaols',
            field=models.TextField(max_length=5000, verbose_name='our_gaols'),
        ),
        migrations.AlterField(
            model_name='about',
            name='our_mission',
            field=models.TextField(max_length=5000, verbose_name='our_mission'),
        ),
        migrations.AlterField(
            model_name='about',
            name='what_we_do',
            field=models.TextField(max_length=5000, verbose_name='what_we_do'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=3000, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=250, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='description',
            field=models.TextField(max_length=3000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(max_length=150, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(help_text='this image is display in slider in home page', upload_to='homeImages/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='images',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_image', to='settings.settings', verbose_name='home_image'),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(help_text='this title is display in slider in home page', max_length=150, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='newslitter',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='newslitter',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='newslitter',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='address',
            field=models.CharField(max_length=50, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='fb_link',
            field=models.URLField(verbose_name='fb_link'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='get_in_touch',
            field=models.TextField(max_length=1000, verbose_name='get_in_touch'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='instagram_link',
            field=models.URLField(verbose_name='instagram_link'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=models.ImageField(upload_to='setting/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='site_name',
            field=models.CharField(max_length=50, verbose_name='site_name'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='twitter_link',
            field=models.URLField(verbose_name='twitter_link'),
        ),
    ]
