# Generated by Django 4.2.10 on 2024-06-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_alter_about_image_alter_about_our_gaols_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='title',
            field=models.CharField(max_length=150, verbose_name='title'),
        ),
    ]
