# Generated by Django 4.2.10 on 2024-06-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_alter_faq_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=250, verbose_name='username'),
        ),
    ]
