# Generated by Django 4.2.10 on 2024-07-02 09:24

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_images_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='our_gaols',
        ),
        migrations.RemoveField(
            model_name='about',
            name='our_mission',
        ),
        migrations.RemoveField(
            model_name='about',
            name='what_we_do',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='description',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='title',
        ),
        migrations.RemoveField(
            model_name='images',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='images',
            name='title',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='description',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='get_in_touch',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='site_name',
        ),
        migrations.CreateModel(
            name='SettingsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('site_name', models.CharField(max_length=50, verbose_name='site_name')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
                ('get_in_touch', models.TextField(max_length=1000, verbose_name='get_in_touch')),
                ('phone', models.CharField(max_length=30, verbose_name='phone')),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='settings.settings')),
            ],
            options={
                'verbose_name': 'Settings Translation',
                'db_table': 'settings_settings_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='ImagesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(help_text='this title is display in slider in home page', max_length=150, verbose_name='title')),
                ('offer', models.CharField(blank=True, max_length=250, null=True, verbose_name='offer')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='settings.images')),
            ],
            options={
                'verbose_name': 'Home Images Translation',
                'db_table': 'settings_images_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='FAQTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.TextField(max_length=3000, verbose_name='description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='settings.faq')),
            ],
            options={
                'verbose_name': 'FAQ Translation',
                'db_table': 'settings_faq_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='AboutTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('what_we_do', models.TextField(max_length=5000, verbose_name='what_we_do')),
                ('our_mission', models.TextField(max_length=5000, verbose_name='our_mission')),
                ('our_gaols', models.TextField(max_length=5000, verbose_name='our_gaols')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='settings.about')),
            ],
            options={
                'verbose_name': 'About Translation',
                'db_table': 'settings_about_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
