# Generated by Django 4.2.10 on 2024-07-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_remove_about_our_gaols_remove_about_our_mission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='twitter_link',
        ),
        migrations.AddField(
            model_name='settings',
            name='snap_link',
            field=models.URLField(default='', verbose_name='snapchat_link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='tiktok_link',
            field=models.URLField(default='', verbose_name='tiktok_link'),
            preserve_default=False,
        ),
    ]
