# Generated by Django 4.2.10 on 2024-07-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_remove_settings_twitter_link_settings_snap_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='phone2',
            field=models.CharField(default='', max_length=30, verbose_name='phone2'),
            preserve_default=False,
        ),
    ]
