# Generated by Django 4.2.10 on 2024-06-27 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Orders', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Order Products', 'verbose_name_plural': 'Order Products'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payments', 'verbose_name_plural': 'Payment'},
        ),
    ]
