# Generated by Django 4.2.10 on 2024-06-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_remove_product_prdbrand_delete_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
