# Generated by Django 4.2.10 on 2024-06-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_subcategory_options_alter_product_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Products', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'Product Images', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='reviewrating',
            options={'verbose_name': 'Rating', 'verbose_name_plural': 'Rating'},
        ),
    ]
