# Generated by Django 4.2.10 on 2024-07-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_product_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRNumber',
            field=models.PositiveIntegerField(default=0, verbose_name='PRNumber'),
        ),
    ]
