# Generated by Django 4.2.10 on 2024-07-08 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_product_prnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_subcategory', to='products.subcategory', verbose_name='product Category'),
            preserve_default=False,
        ),
    ]
