# Generated by Django 4.2.10 on 2024-07-27 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_alter_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaravanImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='caravanimages/', verbose_name='caravan images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caravan_image', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Caravan Images',
                'verbose_name_plural': 'Caravan Images',
            },
        ),
    ]
